<?php
/**
 * ADMIN/BACKUP.PHP — Database Backup Download
 * Download full .sql backup of premium_store database
 */
$pageTitle = 'Backup Database';
require_once __DIR__ . '/../includes/admin_header.php';

// Database info
$tables = $conn->query("SHOW TABLE STATUS FROM premium_store");
$tableList = [];
$totalSize = 0;
while ($t = $tables->fetch_assoc()) {
    $size = $t['Data_length'] + $t['Index_length'];
    $totalSize += $size;
    $tableList[] = [
        'name' => $t['Name'],
        'rows' => $t['Rows'],
        'size' => $size,
        'engine' => $t['Engine'],
        'updated' => $t['Update_time']
    ];
}

// Handle download
if (isset($_GET['download']) && $_GET['download'] === '1') {
    $dbName = 'premium_store';
    $filename = "backup_{$dbName}_" . date('Y-m-d_His') . '.sql';
    
    header('Content-Type: application/sql');
    header("Content-Disposition: attachment; filename=\"{$filename}\"");
    header('Pragma: no-cache');
    header('Expires: 0');
    
    echo "-- ═══════════════════════════════════\n";
    echo "-- Backup: {$dbName}\n";
    echo "-- Date: " . date('Y-m-d H:i:s') . "\n";
    echo "-- Generated by Natsy Premiums Admin\n";
    echo "-- ═══════════════════════════════════\n\n";
    echo "CREATE DATABASE IF NOT EXISTS `{$dbName}`;\n";
    echo "USE `{$dbName}`;\n\n";
    
    $tables = $conn->query("SHOW TABLES");
    while ($row = $tables->fetch_row()) {
        $table = $row[0];
        
        // CREATE TABLE
        $create = $conn->query("SHOW CREATE TABLE `{$table}`")->fetch_row();
        echo "-- Table: {$table}\n";
        echo "DROP TABLE IF EXISTS `{$table}`;\n";
        echo $create[1] . ";\n\n";
        
        // INSERT DATA
        $data = $conn->query("SELECT * FROM `{$table}`");
        if ($data->num_rows > 0) {
            while ($r = $data->fetch_assoc()) {
                $vals = array_map(function($v) use ($conn) {
                    return $v === null ? 'NULL' : "'" . $conn->real_escape_string($v) . "'";
                }, array_values($r));
                echo "INSERT INTO `{$table}` VALUES (" . implode(',', $vals) . ");\n";
            }
            echo "\n";
        }
    }
    exit;
}

function formatBytes($bytes) {
    if ($bytes < 1024) return $bytes . ' B';
    if ($bytes < 1048576) return round($bytes / 1024, 1) . ' KB';
    return round($bytes / 1048576, 2) . ' MB';
}
?>

<!-- Header -->
<div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-5 anim-up d1">
    <div>
        <h1 class="text-lg font-black" style="color:var(--text)"><i class="ri-database-2-fill text-green-500"></i> Backup Database</h1>
        <p class="text-[11px]" style="color:var(--muted)">Unduh cadangan database untuk keamanan data</p>
    </div>
    <a href="?download=1" class="btn btn-primary"><i class="ri-download-2-fill"></i> Download .SQL Backup</a>
</div>

<!-- Stats -->
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5 anim-up d2">
    <div class="admin-card flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl flex items-center justify-center" style="background:rgba(34,197,94,0.1)">
            <i class="ri-database-2-fill text-lg text-green-500"></i>
        </div>
        <div>
            <p class="text-[10px] font-semibold" style="color:var(--muted)">UKURAN DATABASE</p>
            <p class="text-base font-black" style="color:var(--text)"><?= formatBytes($totalSize) ?></p>
        </div>
    </div>
    <div class="admin-card flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl flex items-center justify-center" style="background:rgba(59,130,246,0.1)">
            <i class="ri-table-fill text-lg text-blue-500"></i>
        </div>
        <div>
            <p class="text-[10px] font-semibold" style="color:var(--muted)">TOTAL TABEL</p>
            <p class="text-base font-black" style="color:var(--text)"><?= count($tableList) ?></p>
        </div>
    </div>
    <div class="admin-card flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl flex items-center justify-center" style="background:rgba(168,85,247,0.1)">
            <i class="ri-time-fill text-lg text-purple-500"></i>
        </div>
        <div>
            <p class="text-[10px] font-semibold" style="color:var(--muted)">WAKTU SERVER</p>
            <p class="text-base font-black" style="color:var(--text)"><?= date('d M Y H:i') ?></p>
        </div>
    </div>
</div>

<!-- Table Details -->
<div class="admin-card anim-up d3" style="padding:0;overflow:hidden">
    <div class="px-5 py-4" style="border-bottom:1px solid var(--border)">
        <h3 class="text-xs font-bold" style="color:var(--text)">Detail Tabel</h3>
    </div>
    <div class="overflow-x-auto">
        <table class="admin-table">
            <thead>
                <tr><th>Tabel</th><th>Rows</th><th>Engine</th><th>Ukuran</th><th>Terakhir Update</th></tr>
            </thead>
            <tbody>
                <?php foreach ($tableList as $tbl): ?>
                <tr>
                    <td class="text-xs font-bold font-mono" style="color:var(--text)"><?= htmlspecialchars($tbl['name']) ?></td>
                    <td class="text-xs" style="color:var(--text2)"><?= number_format($tbl['rows']) ?></td>
                    <td><span class="badge badge-info"><?= $tbl['engine'] ?></span></td>
                    <td class="text-xs" style="color:var(--muted)"><?= formatBytes($tbl['size']) ?></td>
                    <td class="text-[11px]" style="color:var(--muted)"><?= $tbl['updated'] ? date('d M Y H:i', strtotime($tbl['updated'])) : '-' ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Tips -->
<div class="admin-card mt-4 anim-up d4" style="border-color:rgba(59,130,246,0.2);background:rgba(59,130,246,0.04)">
    <div class="flex items-start gap-3">
        <i class="ri-lightbulb-fill text-blue-500 text-lg mt-0.5"></i>
        <div>
            <p class="text-xs font-bold mb-1" style="color:var(--text)">Tips Keamanan Data</p>
            <ul class="text-[11px] space-y-1" style="color:var(--muted)">
                <li>• Download backup secara rutin (minimal 1x per minggu)</li>
                <li>• Simpan file backup di lokasi terpisah (Google Drive, USB, dll)</li>
                <li>• Untuk restore, import file .sql ke phpMyAdmin atau terminal MySQL</li>
                <li>• Backup sebelum melakukan perubahan besar pada database</li>
            </ul>
        </div>
    </div>
</div>

<?php require_once __DIR__ . '/../includes/admin_footer.php'; ?>
